### ISSUE TITLE
Double apply of ".Note" class to a note

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#11]
See display output and structure. The "Note" class is added both to the paragraph and the outer div and causes double styling (esp. padding). It should only apply once.

Output:
![screen shot 2018-07-09 at 5 02 15 pm](https://user-images.githubusercontent.com/11865/42441081-fadb9776-8399-11e8-85b9-ff6320d2729e.png)

Structure:
![screen shot 2018-07-09 at 5 02 22 pm](https://user-images.githubusercontent.com/11865/42441080-faae40be-8399-11e8-9241-6b6ab4e6c1b5.png)

**Comment by opoudjis** [comment]
Fixed in isodoc

**Comment by ronaldtse** [comment]
My bundle update isn't showing an updated isodoc (0.8.1), has it been released?

**Comment by opoudjis** [comment]
No. I was wanting to hold off on releases until RSD is put to bed; could you pull and compile isodoc locally?

**Comment by ronaldtse** [comment]
Yes this is fixed. Thanks! However the ".Note <p>" still takes up too much space... I'll see if I can change the gem.

**Comment by ronaldtse** [comment]
Spacing is fixed. No more followups needed here.
