### ISSUE TITLE
Word: image sizes stretched

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#15]
Code:
```
image::myimage.png[width=600]
```

In HTML it looks fine:
![screen shot 2018-07-12 at 9 38 41 am](https://user-images.githubusercontent.com/11865/42607825-7441fa8c-85b7-11e8-90b2-71a5d5720816.png)

In Word it looks vertically stretched:
![screen shot 2018-07-12 at 9 39 48 am](https://user-images.githubusercontent.com/11865/42607836-8acd11ec-85b7-11e8-9886-32d14f43d148.png)

In particular, if I right-click on image and select "Size and Position" it shows this:

![screen shot 2018-07-12 at 9 40 47 am](https://user-images.githubusercontent.com/11865/42607867-ae419daa-85b7-11e8-8c9f-d5603d7a7af9.png)

Notice the width is set to "28%" (this figure changes depending on the original image aspect ratio) -- if you press "Reset" it fixes the aspect ratio.

**Comment by opoudjis** [comment]
Fixed in isodoc and html2doc

**Comment by opoudjis** [comment]
Note that "auto" will not survive into DOC output (or for that matter HTML output): all images sizes are checked to see if they are too big for rendering, and will be populated in the process.
