### ISSUE TITLE
"NOTE: " styling missing in PDF version

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#16]
Notes are rendered as text with shadow but not with the yellow background seen in HTML.

PDF:
![screen shot 2018-07-12 at 7 37 38 pm](https://user-images.githubusercontent.com/11865/42630894-15d92e12-860b-11e8-962b-8276b0be5f9b.png)

HTML:
![screen shot 2018-07-12 at 7 37 31 pm](https://user-images.githubusercontent.com/11865/42630895-1611100c-860b-11e8-907d-da9e57215c6f.png)

**Comment by opoudjis** [comment]
Pierre had indeed disabled the background colour for notes in his stylesheet. I agree with him about doing that, but you're the boss, so putting it back in.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
