### ISSUE TITLE
Styling issue on lists

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#3]
The "before:: content" CSS list-item style (the "-" minus signs for unnumbered bullets) are interfering with the numbered bullets like this:

![screen shot 2018-06-20 at 6 50 16 pm](https://user-images.githubusercontent.com/11865/41654098-e6d6bde8-74ba-11e8-96a4-30fa192b14e5.png)

In addition, the list items are all shifted beyond the left side of content.

The last issue is this -- the "padding: 1.2em" on the `.example` class is causing lists within an example block to be hidden because there is no enough space. 

![screen shot 2018-06-20 at 6 51 35 pm](https://user-images.githubusercontent.com/11865/41654145-132cb0a0-74bb-11e8-9e93-1e19c9f0412b.png)

**Comment by opoudjis** [comment]
Constrained before:: dash to ul. (I do not understand why Pierre didn't constrain it.) 

Constrained the padding on example to left and right.

I've checked in the fixes, but @ronaldtse  you haven't supplied example HTML; could you please confirm?

**Comment by ronaldtse** [comment]
Confirmed fixed!

Last issue: `<ol>`s are still shifted beyond left border of content.

![screen shot 2018-06-20 at 10 13 02 pm](https://user-images.githubusercontent.com/11865/41663956-3759efd0-74d7-11e8-9158-3e4aae45a7f3.png)

**Comment by ronaldtse** [comment]
Once this is fixed please help bump version. Thanks!
