### ISSUE TITLE
Word output for RSD format

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#4]
This is a new use case I realized -- the need for adding review edits and suggesting comments. We can use Word output for this sort of thing (unless we want to create patches based on the HTML output).

@opoudjis can we create a default Word output for Metanorma formats (including RSD)?

**Comment by opoudjis** [comment]
... Wait, there *is* a Word output already included in RSD. I'm not 100% about the footer size, but it's there.

I'm reluctant to include a generic Word output in all Metanorma gems, but copying it across is simple enough. As you know, I am treating the RSD gem as the basis of other customisations; the RSD Word template is useful for that purpose too.

**Comment by opoudjis** [comment]
@ronaldtse What is the status of this ticket? And how does it integrate with https://github.com/riboseinc/isodoc-style/issues/3?

**Comment by opoudjis** [comment]
I'll add that  riboseinc/isodoc-style#3, reading in annotations from HTML back into Asciidoctor, is bad enough; reading them in from Word is going to be so much worse, I'm likely to refuse to do it. Strongly urge you deprecate reading annotations out of Word in favour of reading them out of HTML.

**Comment by ronaldtse** [comment]
OK so if we already have RSD Word, that's great, let's close this ticket.

**Comment by ronaldtse** [comment]
I'm closing this ticket since we already have Word output -- the Word annotation suggestion will move to a separate issue. Thanks!
