### ISSUE TITLE
New document types for internal documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#5]
Internal documents:

* Policy and Procedures
* Proposal

Instead of TC/SC/secretariat we just need a "committee" or "working group". These will require versioning in the way we discussed before (it's not documented in the AsciiISO guidance?).

**Comment by opoudjis** [comment]
Yes, and I think I'm already overruling TC/SC in RSD and all the other gems.

Which versioning are you referring to? Single version number?

How to P&P and Proposals differ from standards? Do they have different schemas, or just different front pages?

**Comment by ronaldtse** [comment]
Sorry for being hand-wavy. Basically, just different front pages. Same schema.  The only things that needs changing:

1. Document type "name" and where it is displayed.
2. The rev-date should be shown on the front page.

**Comment by opoudjis** [comment]
Versioning is documented in the README of asciidoctor-iso, as the `:draft` document attribute. The Guidance document does not repeat the list of document attributes from the README.

**Comment by opoudjis** [comment]
The document type is already a metadata field in the template so (1) does not require any change.

Which means the only change I can tell at all is, rev-date is included in the front page for policies and for proposals, but not for standards.

**Comment by opoudjis** [comment]
Let me know if this is what you had in mind.
[HTML.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2154917/HTML.zip)

**Comment by ronaldtse** [comment]
@opoudjis it might be better if @pierrefortier helps out here 😉 

@pierrefortier could you help style the RSD style for these two new document types? Thanks!

**Comment by pierrefortier** [comment]
Sure thing!

**Comment by opoudjis** [comment]
@ronaldtse: Word too or just HTML?

@pierrefortier: Note there has been some refactoring to your underlying CSS, and to the IDs of tags.

**Comment by ronaldtse** [comment]
Both Word and HTML should look similar, thanks!

**Comment by pierrefortier** [comment]
Here's a quick update. I made the HTML match my previous styling, and took a jab at the Word document. Not sure how close they're supposed to be, so I kept it minimal for now. I can tweak it of course. :)

[DOC.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2157327/DOC.zip)
[HTML.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2157328/HTML.zip)

**Comment by opoudjis** [comment]
This output needs your review, @ronaldtse

**Comment by ronaldtse** [comment]
@pierrefortier sorry for the delay. The HTML style looks exactly like CSD rather than RSD -- perhaps there's a mistake?

For the Doc file, can we try a better design (clean, avant-garde) and also more consistent fonts?

For example, in the screenshot below, the section header font is too narrow, and we're already mixing Arial, Calibri, and Garamond...

<img width="869" alt="screen shot 2018-07-07 at 2 51 16 pm" src="https://user-images.githubusercontent.com/11865/42407851-72329190-81f5-11e8-8585-382072763409.png">

@opoudjis I noticed that the last section of the ToC is bleeding onto the next page. Is this something we need to fix in the actual gem, or is this just an artifact here?

**Comment by opoudjis** [comment]
The font selections will be taken care of in the stylesheet for Word (just as they are in the generation of the HTML), so I'm not too worried about that; just tell me what the body and header fonts are meant to be, @pierrefortier. The stylesheet as is is only going to use one or two fonts in the document at all, unless I tell it otherwise.

**Comment by opoudjis** [comment]
Fixed ToC.

**Comment by ronaldtse** [comment]
@opoudjis thanks. I didn’t realize the lack of page break after ToC was inherited from M3D, in that case we should also fix M3D the same way. It’s too strange to not have a break after ToC.

**Comment by ronaldtse** [comment]
I don’t have an official answer but according to their other samples it looks like it was a bug.

**Comment by pierrefortier** [comment]
Sorry about the mix-up -- I did en up using the wrong style for that one. Here is the correct version:

[rfc6350-html-styling-v2.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2174078/rfc6350-html-styling-v2.zip)

As for the word doc, @opoudjis I'd say use Arial for the body and Arial Narrow for the titles. My motivation for Arial is that I'm assuming we want to stick to system fonts to ensure compatibility, and it's pretty close to what's used in the html.

**Comment by ronaldtse** [comment]
@pierrefortier this style works -- the fine print (copyright) is a bit too fine (let's change to `0.9em` from `0.8em`), but it's good to go!

**Comment by pierrefortier** [comment]
Great! Here's the update. 

[rfc6350-html-styling-v3.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2175867/rfc6350-html-styling-v3.zip)

**Comment by opoudjis** [comment]
@pierrefortier, that 0.9em to 0.8em was the only update, right? Because I do this by eyeball, and I've just finished copying  the style across.

**Comment by pierrefortier** [comment]
Correct, that was the only change.
________________________________

**Comment by opoudjis** [comment]
Confirmed that it is.

This is now the output of the gem:

[RSD.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2176062/RSD.zip)

**Comment by ronaldtse** [comment]
@pierrefortier it turns out that Arial Narrow is rather funny looking as headers. Let's just have Arial instead... Thanks!

**Comment by opoudjis** [comment]
I set the Word fonts. Arial is now set as header font.

Publication date: we have not provided it anywhere in the Metanorma gem suite for the current document; `docyear`, which already appears in the template (after the document ID number) is the copyright-year document attribute, which is the current year if the document attribute is not provided. I don't see a compelling reason to override that behaviour, but I am making the year more prominent in the title pages.

In the HTML, I'm putting it next to "Ribose Group Inc." in the HTML. So, with docyear = copyright year, draftinto including latest document revision date:

````
<div class="coverpage-doc-identity">
    <div class="doc-number">
      <span class="docnumber">{{ docnumber }}</span>
      <span class="docnumber-separator">:</span>
      <span class="docyear">{{ docyear }} {{ draftinfo }}</span>
    </div>

  <div class="coverpage-title">
      <span class="title-first">{{ doctitle }}</span>
    </div>
  </div>

  <div class="coverpage-logo">
    <span>Ribose Group Inc. {{ docyear }}</span>
  </div>
````

For the Word document, I've put it at the bottom of the page.

@ronaldtse Please review.

[RSD 20180710.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2179558/RSD.20180710.zip)

**Comment by ronaldtse** [comment]
@opoudjis I thought we already use `:revdate:` for the publication date? The `:revdate:` is indeed shown with the Proposal type?

**Comment by opoudjis** [comment]
`:revdate` is the YYYY-MM-DD date of the latest draft, and is displayed as such: it ends up inside of the _draftinfo_ template field. `:copyright-year:` is taken as the year of publication, and ends up as the _docyear_ template field. They are distinct, and finalised published documents are not meant to have a `:revdate:` at all.

**Comment by opoudjis** [comment]
@ronaldtse, is action required here?

**Comment by ronaldtse** [comment]
Yes, could we display the publication date for these document types? Thanks!

* policy-and-procedures
* supporting-document
* report
* legal
* proposal

**Comment by opoudjis** [comment]
Please indicate *where* to display the publication date. I am now putting it under the title, next to "Ribose Group Inc."

**Comment by ronaldtse** [comment]
Looks great to me. Thanks! Feel free to close this.
