### ISSUE TITLE
Style issues with dl/dt/dd

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#7]
The current styling still shows `<dt>/<dd>` on separate lines. They should either be on the same line or in a table (same row).

![screen shot 2018-07-09 at 7 19 59 am](https://user-images.githubusercontent.com/11865/42425054-7844cd6e-8349-11e8-93e3-496e4deeec78.png)

**Comment by opoudjis** [comment]
Also not getting this behaviour, either.

**Comment by opoudjis** [comment]
Please check again?

**Comment by ronaldtse** [comment]
It's working for me now. Thanks!
