### ISSUE TITLE
Add label "classification"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rsd#9]
Want to add a label called "classification" that takes free text and shows on the cover page, right below the document identifier. This is for security level classification, e.g., "confidential", "client confidential", etc.

**Comment by opoudjis** [comment]
This will be a new element for RSD; it is not likely to apply to other, public standards.

**Comment by ronaldtse** [comment]
Correct. Thanks!

**Comment by opoudjis** [comment]
I've implemented this; tell me if this is where you want it and what you want it to look like. The document attribute is `:security`.

[security.zip](https://github.com/riboseinc/asciidoctor-rsd/files/2176365/security.zip)

**Comment by ronaldtse** [comment]
This works. Thanks!
